app = "autoguru-api"
primary_region = "sin"   # Singapore – close to India

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  # paste your real Mongo string here
  MONGO_URI = "mongodb+srv://santhosher2011_db_user:lQGQTUNNY28PIafo@cars.dysiv3k.mongodb.net/autoguru?retryWrites=true&w=majority&appName=cars"
  REDIS_URL = "redis://default:6379"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]