services:
  - type: web
    name: autoguru-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://santhosher2011_db_user:lQGQTUNNY28PIafo@cars.dysiv3k.mongodb.net/autoguru?retryWrites=true&w=majority&appName=cars"
      - key: REDIS_URL
        value: "redis://default:6379"