from datetime import datetime, timedelta
from jose import jwt
from passlib.context import CryptContext
pwd_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")
def create_access_token(data: dict): ...
def verify_password(plain, hashed): ...
